sudo: required

language: cpp
compiler:
- gcc
- clang

before_install:
- git checkout $TRAVIS_BRANCH

- bii-support/travis/git/configure.sh

install:
- bii-support/travis/install/all-headless.sh

- export TRAVIS_CXX=$CXX

script:
- bii-support/linux/build/default.sh
- bii-support/linux/build/test.sh

after_success:
  # note: this attempts to publish ALL blocks under blocks/
- bii-support/travis/publish/biicode.sh

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - BII_USER=azriel
    # BII_PASSWORD
  - secure: "hvFCHhclzfFYlh5crvyNPlg0U46JVKsEJzyKlt4ByNgbp3eOL6E6pruZqxqEYQDz3AGn3yP8yAoHie+sM7FpNQvbC3kSMDbHHICbNLzgn0ho75xBgly4ZBA0POcgvjU7TA5qE1LhgUmPunXNOmWGoVRCfnYtB2wSrCMKXWLjABX3CAH0TEp4kmylOgg5NmPcl1VejQi9x2AoIleLIj3MaUWHUbGsNtpYG8jnRXuQ8rRbSbQEQU/xt0zNebni+1TQhlswv00UruGfM+ABhqRe95j1qCHU5TslhjULAUoadV/mc5N3yWbpEnH7ZHHziMPtrPlquXe8sPXnOnMAugTrkAgYDTxxS6+phnAn1IOtiPCiCWROdRmBWgup8sHv5E3Ds4I5vTKbd1COzneJm7N3/A443fUnMYg6viJA/dLpSYFHG4GXNJTOLlTzK6xbGp9z0PfCYzaLeUpzrA/Uk6dAjy7JnQIC2J5Bm+rbYBhrJcEz4NU3iOUCfoqXNBR19QeUg0s3//XAyIIv3ssm7RtyEBDgJCNx8b+hrqa+1qnPIFgD1KXrSA1g7eXtkgsm1RnKCBWP9JyWujpekD7GC0u5oX3Wgb8coekCuUYlJi2P3axnaI4psVqRuhsjl95pMKOR4lk+afd3O1RhGeQIYBSDPl9zcX8p+tVyT8gJPaQjdQ4="
  matrix:
  - BUILD_SHARED_LIBS=OFF
  - BUILD_SHARED_LIBS=ON